{
    'name': 'Centro Sanitario - Área Social',
    'version': '1.0.1',
    'category': 'Healthcare',
    'summary': 'Módulo para gestión de atenciones, informes sociales y gestiones del área social (trabajo social y educación social)',
    'author': 'Equilibrium Dev Team',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'calendar',
        'cs_resident',
        'cs_patient_followup_forms',
        'cs_psychology',
        'cs_medical_care',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/ir_sequence.xml',
        'views/social_work_calendar_views.xml',
        'views/cs_social_session_views.xml',
        'views/cs_social_report_views.xml',
        'views/cs_social_procedure_views.xml',
        'views/resident_social_work_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
